# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_transport_mode import VTApiPlaneraResaWebV4ModelsJourneyTransportMode  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsJourneyTransportMode(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsJourneyTransportMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaWebV4ModelsJourneyTransportMode(self):
        """Test VTApiPlaneraResaWebV4ModelsJourneyTransportMode"""
        # inst = VTApiPlaneraResaWebV4ModelsJourneyTransportMode()

if __name__ == '__main__':
    unittest.main()
