# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_valid_time_interval_api_model import VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel:
        """Test VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel(
                valid_from = '',
                valid_until = ''
            )
        else:
            return VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
