# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_zone_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel:
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel(
                id = 56
            )
        else:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
