# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.positions_api import PositionsApi  # noqa: E501


class TestPositionsApi(unittest.TestCase):
    """PositionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PositionsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_positions_get(self) -> None:
        """Test case for positions_get

        Returns journey positions within a bounding box  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
