# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_departures_and_arrivals_line_api_model import VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel:
        """Test VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel(
                gid = '',
                name = '',
                short_name = '',
                designation = '',
                background_color = '',
                foreground_color = '',
                border_color = '',
                transport_mode = 'unknown',
                transport_sub_mode = 'unknown',
                is_wheelchair_accessible = True
            )
        else:
            return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
