# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_core_models_severity import VTApiPlaneraResaCoreModelsSeverity  # noqa: E501

class TestVTApiPlaneraResaCoreModelsSeverity(unittest.TestCase):
    """VTApiPlaneraResaCoreModelsSeverity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaCoreModelsSeverity(self):
        """Test VTApiPlaneraResaCoreModelsSeverity"""
        # inst = VTApiPlaneraResaCoreModelsSeverity()

if __name__ == '__main__':
    unittest.main()
