# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_location_by_coordinates_type import VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsLocationByCoordinatesType(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaWebV4ModelsLocationByCoordinatesType(self):
        """Test VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType"""
        # inst = VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType()

if __name__ == '__main__':
    unittest.main()
