# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.stop_areas_api import StopAreasApi  # noqa: E501


class TestStopAreasApi(unittest.TestCase):
    """StopAreasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StopAreasApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_stop_areas_stop_area_gid_arrivals_details_reference_details_get(self) -> None:
        """Test case for stop_areas_stop_area_gid_arrivals_details_reference_details_get

        Returns details about an arrival.  # noqa: E501
        """
        pass

    def test_stop_areas_stop_area_gid_arrivals_get(self) -> None:
        """Test case for stop_areas_stop_area_gid_arrivals_get

        Returns arrivals to the specified stop area at the specified time.  # noqa: E501
        """
        pass

    def test_stop_areas_stop_area_gid_departures_details_reference_details_get(self) -> None:
        """Test case for stop_areas_stop_area_gid_departures_details_reference_details_get

        Returns details about a departure.  # noqa: E501
        """
        pass

    def test_stop_areas_stop_area_gid_departures_get(self) -> None:
        """Test case for stop_areas_stop_area_gid_departures_get

        Returns departures from the specified stop area at the specified time.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
