# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_occupancy_information_source import VTApiPlaneraResaWebV4ModelsOccupancyInformationSource  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsOccupancyInformationSource(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsOccupancyInformationSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaWebV4ModelsOccupancyInformationSource(self):
        """Test VTApiPlaneraResaWebV4ModelsOccupancyInformationSource"""
        # inst = VTApiPlaneraResaWebV4ModelsOccupancyInformationSource()

if __name__ == '__main__':
    unittest.main()
