# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_link_segment_orientation import VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsLinkSegmentOrientation(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaWebV4ModelsLinkSegmentOrientation(self):
        """Test VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation"""
        # inst = VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation()

if __name__ == '__main__':
    unittest.main()
