# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_coordinate_api_model import VTApiPlaneraResaWebV4ModelsCoordinateApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsCoordinateApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsCoordinateApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsCoordinateApiModel:
        """Test VTApiPlaneraResaWebV4ModelsCoordinateApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsCoordinateApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsCoordinateApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsCoordinateApiModel(
                latitude = 1.337,
                longitude = 1.337,
                elevation = 1.337,
                is_on_trip_leg = True,
                is_trip_leg_start = True,
                is_trip_leg_stop = True
            )
        else:
            return VTApiPlaneraResaWebV4ModelsCoordinateApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsCoordinateApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsCoordinateApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
