# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_punch_configuration_duration_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel:
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel(
                unit = 'hours',
                amount = 56
            )
        else:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
