# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_core_models_position_transport_mode import VTApiPlaneraResaCoreModelsPositionTransportMode  # noqa: E501

class TestVTApiPlaneraResaCoreModelsPositionTransportMode(unittest.TestCase):
    """VTApiPlaneraResaCoreModelsPositionTransportMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaCoreModelsPositionTransportMode(self):
        """Test VTApiPlaneraResaCoreModelsPositionTransportMode"""
        # inst = VTApiPlaneraResaCoreModelsPositionTransportMode()

if __name__ == '__main__':
    unittest.main()
