# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_core_models_time_validity_unit import VTApiPlaneraResaCoreModelsTimeValidityUnit  # noqa: E501

class TestVTApiPlaneraResaCoreModelsTimeValidityUnit(unittest.TestCase):
    """VTApiPlaneraResaCoreModelsTimeValidityUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaCoreModelsTimeValidityUnit(self):
        """Test VTApiPlaneraResaCoreModelsTimeValidityUnit"""
        # inst = VTApiPlaneraResaCoreModelsTimeValidityUnit()

if __name__ == '__main__':
    unittest.main()
