# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_core_models_traveller_category import VTApiPlaneraResaCoreModelsTravellerCategory  # noqa: E501

class TestVTApiPlaneraResaCoreModelsTravellerCategory(unittest.TestCase):
    """VTApiPlaneraResaCoreModelsTravellerCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaCoreModelsTravellerCategory(self):
        """Test VTApiPlaneraResaCoreModelsTravellerCategory"""
        # inst = VTApiPlaneraResaCoreModelsTravellerCategory()

if __name__ == '__main__':
    unittest.main()
