# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_journeys_link_endpoint_api_model import VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel:
        """Test VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel(
                gid = '',
                name = '0',
                location_type = 'unknown',
                latitude = 1.337,
                longitude = 1.337,
                planned_time = '0',
                estimated_time = '',
                estimated_otherwise_planned_time = '',
                notes = [
                    openapi_client.models.vt/api_planera_resa/core/models/note.VT.ApiPlaneraResa.Core.Models.Note(
                        type = '', 
                        severity = 'unknown', 
                        text = '', )
                    ]
            )
        else:
            return VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel(
                name = '0',
                location_type = 'unknown',
                planned_time = '0',
        )
        """

    def testVTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsJourneysLinkEndpointApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
