# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_punch_configuration_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel:
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel(
                quota = 56,
                duration = openapi_client.models.vt/api_planera_resa/web/v4/models/journey_details/punch_configuration_duration_api_model.VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.PunchConfigurationDurationApiModel(
                    unit = 'hours', 
                    amount = 56, )
            )
        else:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
