# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_positions_journey_position_api_model import VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel:
        """Test VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel(
                details_reference = '',
                line = openapi_client.models.vt/api_planera_resa/web/v4/models/positions/line_details_api_model.VT.ApiPlaneraResa.Web.V4.Models.Positions.LineDetailsApiModel(
                    name = '', 
                    background_color = '', 
                    foreground_color = '', 
                    border_color = '', 
                    transport_mode = 'unknown', 
                    transport_sub_mode = 'unknown', ),
                notes = [
                    openapi_client.models.vt/api_planera_resa/core/models/note.VT.ApiPlaneraResa.Core.Models.Note(
                        type = '', 
                        severity = 'unknown', 
                        text = '', )
                    ],
                name = '',
                direction = '',
                latitude = 1.337,
                longitude = 1.337
            )
        else:
            return VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
