# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_core_models_transport_sub_mode import VTApiPlaneraResaCoreModelsTransportSubMode  # noqa: E501

class TestVTApiPlaneraResaCoreModelsTransportSubMode(unittest.TestCase):
    """VTApiPlaneraResaCoreModelsTransportSubMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaCoreModelsTransportSubMode(self):
        """Test VTApiPlaneraResaCoreModelsTransportSubMode"""
        # inst = VTApiPlaneraResaCoreModelsTransportSubMode()

if __name__ == '__main__':
    unittest.main()
