# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_ticket_suggestion_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel:
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel(
                product_id = 56,
                product_name = '',
                product_type = 56,
                traveller_category = 'unknown',
                price_in_sek = 1.337,
                time_validity = openapi_client.models.vt/api_planera_resa/web/v4/models/journey_details/time_validity_api_model.VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.TimeValidityApiModel(
                    type = 'unknown', 
                    amount = 56, 
                    unit = 'unknown', 
                    from_date = '2018-11-29', 
                    to_date = '2018-11-30', 
                    from_date_time = '2018-11-30T17:07:10+01:00', 
                    to_date_time = '2018-11-30T17:07:10+01:00', ),
                time_limitation = 'unknown',
                sale_channels = [
                    openapi_client.models.vt/api_planera_resa/web/v4/models/journey_details/channel_api_model.VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.ChannelApiModel(
                        id = 56, 
                        ticket_name = '', )
                    ],
                valid_zones = [
                    openapi_client.models.vt/api_planera_resa/web/v4/models/journey_details/zone_api_model.VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.ZoneApiModel(
                        id = 56, )
                    ],
                product_instance_type = 'static',
                punch_configuration = openapi_client.models.vt/api_planera_resa/web/v4/models/journey_details/punch_configuration_api_model.VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.PunchConfigurationApiModel(
                    quota = 56, 
                    duration = openapi_client.models.vt/api_planera_resa/web/v4/models/journey_details/punch_configuration_duration_api_model.VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.PunchConfigurationDurationApiModel(
                        unit = 'hours', 
                        amount = 56, ), ),
                offer_specification = ''
            )
        else:
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
