# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_core_models_location_type import VTApiPlaneraResaCoreModelsLocationType  # noqa: E501

class TestVTApiPlaneraResaCoreModelsLocationType(unittest.TestCase):
    """VTApiPlaneraResaCoreModelsLocationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaCoreModelsLocationType(self):
        """Test VTApiPlaneraResaCoreModelsLocationType"""
        # inst = VTApiPlaneraResaCoreModelsLocationType()

if __name__ == '__main__':
    unittest.main()
