# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_occupancy_level import VTApiPlaneraResaWebV4ModelsOccupancyLevel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsOccupancyLevel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsOccupancyLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaWebV4ModelsOccupancyLevel(self):
        """Test VTApiPlaneraResaWebV4ModelsOccupancyLevel"""
        # inst = VTApiPlaneraResaWebV4ModelsOccupancyLevel()

if __name__ == '__main__':
    unittest.main()
