# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_transport_sub_mode import VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsJourneyTransportSubMode(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVTApiPlaneraResaWebV4ModelsJourneyTransportSubMode(self):
        """Test VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode"""
        # inst = VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode()

if __name__ == '__main__':
    unittest.main()
