# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vt_api_planera_resa_web_v4_models_departures_and_arrivals_line_details_api_model import VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel  # noqa: E501

class TestVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel(unittest.TestCase):
    """VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel:
        """Test VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel`
        """
        model = VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel()  # noqa: E501
        if include_optional:
            return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel(
                name = '',
                background_color = '',
                foreground_color = '',
                border_color = '',
                transport_mode = 'unknown',
                transport_sub_mode = 'unknown'
            )
        else:
            return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel(
        )
        """

    def testVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel(self):
        """Test VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
