# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation(str, Enum):
    """
    Specifies an orientation of a link segment.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    NORTH = 'north'
    SOUTH = 'south'
    EAST = 'east'
    WEST = 'west'
    NORTHEAST = 'northeast'
    SOUTHEAST = 'southeast'
    NORTHWEST = 'northwest'
    SOUTHWEST = 'southwest'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation:
        """Create an instance of VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation from a JSON string"""
        return VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation(json.loads(json_str))


