# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel(BaseModel):
    """
    Information specifying the interval when valid journey information is available, i.e. when it is possible to search journeys.  # noqa: E501
    """
    valid_from: Optional[StrictStr] = Field(None, alias="validFrom", description="The start time of the interval when valid journey information is available, specified in RFC 3339 format.")
    valid_until: Optional[StrictStr] = Field(None, alias="validUntil", description="The end time of the interval when valid journey information is available, specified in RFC 3339 format.")
    __properties = ["validFrom", "validUntil"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if valid_from (nullable) is None
        # and __fields_set__ contains the field
        if self.valid_from is None and "valid_from" in self.__fields_set__:
            _dict['validFrom'] = None

        # set to None if valid_until (nullable) is None
        # and __fields_set__ contains the field
        if self.valid_until is None and "valid_until" in self.__fields_set__:
            _dict['validUntil'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel.parse_obj({
            "valid_from": obj.get("validFrom"),
            "valid_until": obj.get("validUntil")
        })
        return _obj


