# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaCoreModelsTransportSubMode(str, Enum):
    """
    VTApiPlaneraResaCoreModelsTransportSubMode
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    NONE = 'none'
    VASTTAGEN = 'vasttagen'
    LONGDISTANCETRAIN = 'longdistancetrain'
    REGIONALTRAIN = 'regionaltrain'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaCoreModelsTransportSubMode:
        """Create an instance of VTApiPlaneraResaCoreModelsTransportSubMode from a JSON string"""
        return VTApiPlaneraResaCoreModelsTransportSubMode(json.loads(json_str))


