# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaCoreModelsLocationType(str, Enum):
    """
    VTApiPlaneraResaCoreModelsLocationType
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    STOPAREA = 'stoparea'
    STOPPOINT = 'stoppoint'
    ADDRESS = 'address'
    POINTOFINTEREST = 'pointofinterest'
    METASTATION = 'metastation'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaCoreModelsLocationType:
        """Create an instance of VTApiPlaneraResaCoreModelsLocationType from a JSON string"""
        return VTApiPlaneraResaCoreModelsLocationType(json.loads(json_str))


