# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaCoreModelsSeverity(str, Enum):
    """
    VTApiPlaneraResaCoreModelsSeverity
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    LOW = 'low'
    NORMAL = 'normal'
    HIGH = 'high'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaCoreModelsSeverity:
        """Create an instance of VTApiPlaneraResaCoreModelsSeverity from a JSON string"""
        return VTApiPlaneraResaCoreModelsSeverity(json.loads(json_str))


