# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaCoreModelsTimeLimitation(str, Enum):
    """
    VTApiPlaneraResaCoreModelsTimeLimitation
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    HELTID = 'heltid'
    LAGTRAFIK = 'lagtrafik'
    SKOLKORT04TILL19 = 'skolkort04till19'
    SKOLKORT04TILL22 = 'skolkort04till22'
    SKOLKORT04TILL1930 = 'skolkort04till1930'
    FRITID100 = 'fritid100'
    FRITIDKOMPLEMENT = 'fritidkomplement'
    FRITIDVARDAG19TILL22 = 'fritidvardag19till22'
    FRITIDVARDAG14TILL24 = 'fritidvardag14till24'
    FRITIDKVALLHELG = 'fritidkvallhelg'
    FRITIDKVALLHELGLOV = 'fritidkvallhelglov'
    FRITIDJULSOMMARLOV = 'fritidjulsommarlov'
    FRITIDALE = 'fritidale'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaCoreModelsTimeLimitation:
        """Create an instance of VTApiPlaneraResaCoreModelsTimeLimitation from a JSON string"""
        return VTApiPlaneraResaCoreModelsTimeLimitation(json.loads(json_str))


