# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaCoreModelsPositionTransportMode(str, Enum):
    """
    VTApiPlaneraResaCoreModelsPositionTransportMode
    """

    """
    allowed enum values
    """
    TRAM = 'tram'
    BUS = 'bus'
    FERRY = 'ferry'
    TRAIN = 'train'
    TAXI = 'taxi'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaCoreModelsPositionTransportMode:
        """Create an instance of VTApiPlaneraResaCoreModelsPositionTransportMode from a JSON string"""
        return VTApiPlaneraResaCoreModelsPositionTransportMode(json.loads(json_str))


