# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class VTApiPlaneraResaWebV4ModelsApiError(BaseModel):
    """
    Information about the error.  # noqa: E501
    """
    error_code: Optional[StrictInt] = Field(None, alias="errorCode", description="Error code.")
    error_message: Optional[StrictStr] = Field(None, alias="errorMessage", description="More detailed description of the error.")
    __properties = ["errorCode", "errorMessage"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsApiError:
        """Create an instance of VTApiPlaneraResaWebV4ModelsApiError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if error_message (nullable) is None
        # and __fields_set__ contains the field
        if self.error_message is None and "error_message" in self.__fields_set__:
            _dict['errorMessage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsApiError:
        """Create an instance of VTApiPlaneraResaWebV4ModelsApiError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsApiError.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsApiError.parse_obj({
            "error_code": obj.get("errorCode"),
            "error_message": obj.get("errorMessage")
        })
        return _obj


