# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel(BaseModel):
    """
    Information about ticket validity.  # noqa: E501
    """
    id: Optional[StrictStr] = Field(None, description="The ticket id.")
    is_valid_for_journey: Optional[StrictBool] = Field(None, alias="isValidForJourney", description="Indicates if the ticket is valid for the journey.")
    __properties = ["id", "isValidForJourney"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if id (nullable) is None
        # and __fields_set__ contains the field
        if self.id is None and "id" in self.__fields_set__:
            _dict['id'] = None

        # set to None if is_valid_for_journey (nullable) is None
        # and __fields_set__ contains the field
        if self.is_valid_for_journey is None and "is_valid_for_journey" in self.__fields_set__:
            _dict['isValidForJourney'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel.parse_obj({
            "id": obj.get("id"),
            "is_valid_for_journey": obj.get("isValidForJourney")
        })
        return _obj


