# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt

class VTApiPlaneraResaWebV4ModelsPaginationProperties(BaseModel):
    """
    Pagination information.  # noqa: E501
    """
    limit: Optional[StrictInt] = Field(None, description="The requested number of results.")
    offset: Optional[StrictInt] = Field(None, description="The requested offset in the results array.")
    size: Optional[StrictInt] = Field(None, description="The actual number of returned results.")
    __properties = ["limit", "offset", "size"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsPaginationProperties:
        """Create an instance of VTApiPlaneraResaWebV4ModelsPaginationProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsPaginationProperties:
        """Create an instance of VTApiPlaneraResaWebV4ModelsPaginationProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsPaginationProperties.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsPaginationProperties.parse_obj({
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "size": obj.get("size")
        })
        return _obj


