# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_occupancy_information_source import VTApiPlaneraResaWebV4ModelsOccupancyInformationSource
from openapi_client.models.vt_api_planera_resa_web_v4_models_occupancy_level import VTApiPlaneraResaWebV4ModelsOccupancyLevel

class VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel(BaseModel):
    """
    Contains information about occupancy.  # noqa: E501
    """
    level: Optional[VTApiPlaneraResaWebV4ModelsOccupancyLevel] = None
    source: Optional[VTApiPlaneraResaWebV4ModelsOccupancyInformationSource] = None
    __properties = ["level", "source"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel.parse_obj({
            "level": obj.get("level"),
            "source": obj.get("source")
        })
        return _obj


