# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from openapi_client.models.vt_api_planera_resa_web_v4_models_departures_and_arrivals_service_journey_details_api_model import VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel

class VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel(BaseModel):
    """
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel
    """
    service_journeys: Optional[conlist(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel)] = Field(None, alias="serviceJourneys")
    __properties = ["serviceJourneys"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in service_journeys (list)
        _items = []
        if self.service_journeys:
            for _item in self.service_journeys:
                if _item:
                    _items.append(_item.to_dict())
            _dict['serviceJourneys'] = _items
        # set to None if service_journeys (nullable) is None
        # and __fields_set__ contains the field
        if self.service_journeys is None and "service_journeys" in self.__fields_set__:
            _dict['serviceJourneys'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalDetailsApiModel.parse_obj({
            "service_journeys": [VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel.from_dict(_item) for _item in obj.get("serviceJourneys")] if obj.get("serviceJourneys") is not None else None
        })
        return _obj


