# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_arrival_access_link_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_connection_link_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_departure_access_link_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_destination_link_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_tariff_zone_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_ticket_suggestions_result_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_trip_leg_details_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_occupancy_information_api_model import VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel

class VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel(BaseModel):
    """
    Detailed information about a journey.  # noqa: E501
    """
    departure_access_link: Optional[VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel] = Field(None, alias="departureAccessLink")
    trip_legs: Optional[conlist(VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel)] = Field(None, alias="tripLegs", description="Detailed information, including stops, about the trip legs.")
    connection_links: Optional[conlist(VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel)] = Field(None, alias="connectionLinks", description="A list of ConnectionLinks between TripLegs, when applicable. The internal order of TripLegs and ConnectionLinks is defined by Index-property on the objects.")
    arrival_access_link: Optional[VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel] = Field(None, alias="arrivalAccessLink")
    destination_link: Optional[VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel] = Field(None, alias="destinationLink")
    ticket_suggestions_result: Optional[VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel] = Field(None, alias="ticketSuggestionsResult")
    tariff_zones: Optional[conlist(VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel)] = Field(None, alias="tariffZones", description="The tariff zones that the journey traverses.")
    occupancy: Optional[VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel] = None
    __properties = ["departureAccessLink", "tripLegs", "connectionLinks", "arrivalAccessLink", "destinationLink", "ticketSuggestionsResult", "tariffZones", "occupancy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of departure_access_link
        if self.departure_access_link:
            _dict['departureAccessLink'] = self.departure_access_link.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in trip_legs (list)
        _items = []
        if self.trip_legs:
            for _item in self.trip_legs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tripLegs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in connection_links (list)
        _items = []
        if self.connection_links:
            for _item in self.connection_links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['connectionLinks'] = _items
        # override the default output from pydantic by calling `to_dict()` of arrival_access_link
        if self.arrival_access_link:
            _dict['arrivalAccessLink'] = self.arrival_access_link.to_dict()
        # override the default output from pydantic by calling `to_dict()` of destination_link
        if self.destination_link:
            _dict['destinationLink'] = self.destination_link.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ticket_suggestions_result
        if self.ticket_suggestions_result:
            _dict['ticketSuggestionsResult'] = self.ticket_suggestions_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tariff_zones (list)
        _items = []
        if self.tariff_zones:
            for _item in self.tariff_zones:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tariffZones'] = _items
        # override the default output from pydantic by calling `to_dict()` of occupancy
        if self.occupancy:
            _dict['occupancy'] = self.occupancy.to_dict()
        # set to None if trip_legs (nullable) is None
        # and __fields_set__ contains the field
        if self.trip_legs is None and "trip_legs" in self.__fields_set__:
            _dict['tripLegs'] = None

        # set to None if connection_links (nullable) is None
        # and __fields_set__ contains the field
        if self.connection_links is None and "connection_links" in self.__fields_set__:
            _dict['connectionLinks'] = None

        # set to None if tariff_zones (nullable) is None
        # and __fields_set__ contains the field
        if self.tariff_zones is None and "tariff_zones" in self.__fields_set__:
            _dict['tariffZones'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel.parse_obj({
            "departure_access_link": VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel.from_dict(obj.get("departureAccessLink")) if obj.get("departureAccessLink") is not None else None,
            "trip_legs": [VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel.from_dict(_item) for _item in obj.get("tripLegs")] if obj.get("tripLegs") is not None else None,
            "connection_links": [VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel.from_dict(_item) for _item in obj.get("connectionLinks")] if obj.get("connectionLinks") is not None else None,
            "arrival_access_link": VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel.from_dict(obj.get("arrivalAccessLink")) if obj.get("arrivalAccessLink") is not None else None,
            "destination_link": VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel.from_dict(obj.get("destinationLink")) if obj.get("destinationLink") is not None else None,
            "ticket_suggestions_result": VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel.from_dict(obj.get("ticketSuggestionsResult")) if obj.get("ticketSuggestionsResult") is not None else None,
            "tariff_zones": [VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.from_dict(_item) for _item in obj.get("tariffZones")] if obj.get("tariffZones") is not None else None,
            "occupancy": VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel.from_dict(obj.get("occupancy")) if obj.get("occupancy") is not None else None
        })
        return _obj


