# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr
from openapi_client.models.vt_api_planera_resa_core_models_note import VTApiPlaneraResaCoreModelsNote
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_stop_point_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel

class VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel(BaseModel):
    """
    Information about a call on the trip leg.  # noqa: E501
    """
    stop_point: VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel = Field(..., alias="stopPoint")
    planned_time: constr(strict=True, min_length=1) = Field(..., alias="plannedTime", description="The planned time of the call in RFC 3339 format.")
    estimated_time: Optional[StrictStr] = Field(None, alias="estimatedTime", description="The estimated time of the call in RFC 3339 format.")
    estimated_otherwise_planned_time: Optional[StrictStr] = Field(None, alias="estimatedOtherwisePlannedTime", description="The best known time of the call in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.")
    notes: Optional[conlist(VTApiPlaneraResaCoreModelsNote)] = Field(None, description="An ordered list (most important first) of notes related to the call.")
    __properties = ["stopPoint", "plannedTime", "estimatedTime", "estimatedOtherwisePlannedTime", "notes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "estimated_otherwise_planned_time",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of stop_point
        if self.stop_point:
            _dict['stopPoint'] = self.stop_point.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item in self.notes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['notes'] = _items
        # set to None if estimated_time (nullable) is None
        # and __fields_set__ contains the field
        if self.estimated_time is None and "estimated_time" in self.__fields_set__:
            _dict['estimatedTime'] = None

        # set to None if estimated_otherwise_planned_time (nullable) is None
        # and __fields_set__ contains the field
        if self.estimated_otherwise_planned_time is None and "estimated_otherwise_planned_time" in self.__fields_set__:
            _dict['estimatedOtherwisePlannedTime'] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict['notes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel.parse_obj({
            "stop_point": VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.from_dict(obj.get("stopPoint")) if obj.get("stopPoint") is not None else None,
            "planned_time": obj.get("plannedTime"),
            "estimated_time": obj.get("estimatedTime"),
            "estimated_otherwise_planned_time": obj.get("estimatedOtherwisePlannedTime"),
            "notes": [VTApiPlaneraResaCoreModelsNote.from_dict(_item) for _item in obj.get("notes")] if obj.get("notes") is not None else None
        })
        return _obj


