# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver(str, Enum):
    """
    Specifies a maneuver to be executed for a link segment.
    """

    """
    allowed enum values
    """
    NONE = 'none'
    FROM = 'from'
    TO = 'to'
    ON = 'on'
    LEFT = 'left'
    RIGHT = 'right'
    KEEPLEFT = 'keepleft'
    KEEPRIGHT = 'keepright'
    HALFLEFT = 'halfleft'
    HALFRIGHT = 'halfright'
    KEEPHALFLEFT = 'keephalfleft'
    KEEPHALFRIGHT = 'keephalfright'
    SHARPLEFT = 'sharpleft'
    SHARPRIGHT = 'sharpright'
    KEEPSHARPLEFT = 'keepsharpleft'
    KEEPSHARPRIGHT = 'keepsharpright'
    STRAIGHT = 'straight'
    UTURN = 'uturn'
    ENTER = 'enter'
    LEAVE = 'leave'
    ENTERROUNDABOUT = 'enterroundabout'
    STAYINROUNDABOUT = 'stayinroundabout'
    LEAVEROUNDABOUT = 'leaveroundabout'
    ENTERFERRY = 'enterferry'
    LEAVEFERRY = 'leaveferry'
    CHANGEHIGHWAY = 'changehighway'
    CHECKINFERRY = 'checkinferry'
    CHECKOUTFERRY = 'checkoutferry'
    ELEVATOR = 'elevator'
    ELEVATORDOWN = 'elevatordown'
    ELEVATORUP = 'elevatorup'
    ESCALATOR = 'escalator'
    ESCALATORDOWN = 'escalatordown'
    ESCALATORUP = 'escalatorup'
    STAIRS = 'stairs'
    STAIRSDOWN = 'stairsdown'
    STAIRSUP = 'stairsup'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver:
        """Create an instance of VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver from a JSON string"""
        return VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver(json.loads(json_str))


