# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType(str, Enum):
    """
    The different kinds of detailed information that could be included in a get departure details request.
    """

    """
    allowed enum values
    """
    SERVICEJOURNEYCALLS = 'servicejourneycalls'
    SERVICEJOURNEYCOORDINATES = 'servicejourneycoordinates'
    OCCUPANCY = 'occupancy'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType:
        """Create an instance of VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType from a JSON string"""
        return VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType(json.loads(json_str))


