# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from openapi_client.models.vt_api_planera_resa_web_v4_models_coordinate_api_model import VTApiPlaneraResaWebV4ModelsCoordinateApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_call_details_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_line_details_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel

class VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel(BaseModel):
    """
    Information about a service journey.  # noqa: E501
    """
    gid: Optional[StrictStr] = Field(None, description="16-digit Västtrafik service journey gid that the trip leg is a part of.")
    direction: Optional[StrictStr] = Field(None, description="A description of the direction.")
    line: Optional[VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel] = None
    service_journey_coordinates: Optional[conlist(VTApiPlaneraResaWebV4ModelsCoordinateApiModel)] = Field(None, alias="serviceJourneyCoordinates", description="The coordinates on the service journey.")
    calls_on_service_journey: Optional[conlist(VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel)] = Field(None, alias="callsOnServiceJourney", description="All calls on the service journey.")
    __properties = ["gid", "direction", "line", "serviceJourneyCoordinates", "callsOnServiceJourney"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of line
        if self.line:
            _dict['line'] = self.line.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in service_journey_coordinates (list)
        _items = []
        if self.service_journey_coordinates:
            for _item in self.service_journey_coordinates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['serviceJourneyCoordinates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in calls_on_service_journey (list)
        _items = []
        if self.calls_on_service_journey:
            for _item in self.calls_on_service_journey:
                if _item:
                    _items.append(_item.to_dict())
            _dict['callsOnServiceJourney'] = _items
        # set to None if gid (nullable) is None
        # and __fields_set__ contains the field
        if self.gid is None and "gid" in self.__fields_set__:
            _dict['gid'] = None

        # set to None if direction (nullable) is None
        # and __fields_set__ contains the field
        if self.direction is None and "direction" in self.__fields_set__:
            _dict['direction'] = None

        # set to None if service_journey_coordinates (nullable) is None
        # and __fields_set__ contains the field
        if self.service_journey_coordinates is None and "service_journey_coordinates" in self.__fields_set__:
            _dict['serviceJourneyCoordinates'] = None

        # set to None if calls_on_service_journey (nullable) is None
        # and __fields_set__ contains the field
        if self.calls_on_service_journey is None and "calls_on_service_journey" in self.__fields_set__:
            _dict['callsOnServiceJourney'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel.parse_obj({
            "gid": obj.get("gid"),
            "direction": obj.get("direction"),
            "line": VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel.from_dict(obj.get("line")) if obj.get("line") is not None else None,
            "service_journey_coordinates": [VTApiPlaneraResaWebV4ModelsCoordinateApiModel.from_dict(_item) for _item in obj.get("serviceJourneyCoordinates")] if obj.get("serviceJourneyCoordinates") is not None else None,
            "calls_on_service_journey": [VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel.from_dict(_item) for _item in obj.get("callsOnServiceJourney")] if obj.get("callsOnServiceJourney") is not None else None
        })
        return _obj


