# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaWebV4ModelsOccupancyLevel(str, Enum):
    """
    Represents a level of occupancy.
    """

    """
    allowed enum values
    """
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    INCOMPLETE = 'incomplete'
    MISSING = 'missing'
    NOTPUBLICTRANSPORT = 'notpublictransport'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsOccupancyLevel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsOccupancyLevel from a JSON string"""
        return VTApiPlaneraResaWebV4ModelsOccupancyLevel(json.loads(json_str))


