# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel(BaseModel):
    """
    Information about a channel related to the ticket suggestion.  # noqa: E501
    """
    id: Optional[StrictInt] = Field(None, description="The channel id.")
    ticket_name: Optional[StrictStr] = Field(None, alias="ticketName", description="The channel-specific ticket name, set if the channel is configured to override the default  product name.")
    __properties = ["id", "ticketName"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if ticket_name (nullable) is None
        # and __fields_set__ contains the field
        if self.ticket_name is None and "ticket_name" in self.__fields_set__:
            _dict['ticketName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel.parse_obj({
            "id": obj.get("id"),
            "ticket_name": obj.get("ticketName")
        })
        return _obj


