# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel(str, Enum):
    """
    Unit of duration of validity of a single punch.
    """

    """
    allowed enum values
    """
    HOURS = 'hours'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel from a JSON string"""
        return VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel(json.loads(json_str))


