# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType(str, Enum):
    """
    A subset of LocationType
    """

    """
    allowed enum values
    """
    STOPAREA = 'stoparea'
    STOPPOINT = 'stoppoint'
    POINTOFINTEREST = 'pointofinterest'
    METASTATION = 'metastation'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType:
        """Create an instance of VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType from a JSON string"""
        return VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType(json.loads(json_str))


