# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel(str, Enum):
    """
    Specifies whether or not the product is dynamically based on the journey route.
    """

    """
    allowed enum values
    """
    STATIC = 'static'
    DYNAMIC = 'dynamic'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel from a JSON string"""
        return VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel(json.loads(json_str))


