# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, constr
from openapi_client.models.vt_api_planera_resa_web_v4_models_journeys_stop_area_api_model import VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel

class VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel(BaseModel):
    """
    VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel
    """
    gid: constr(strict=True, min_length=1) = Field(..., description="The 16-digit Västtrafik gid of the stop point.")
    name: constr(strict=True, min_length=1) = Field(..., description="The stop point name.")
    platform: Optional[StrictStr] = Field(None, description="The platform of the stop point.")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The latitude coordinate of the stop point.")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The logitude coordinate of the stop point.")
    stop_area: Optional[VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel] = Field(None, alias="stopArea")
    __properties = ["gid", "name", "platform", "latitude", "longitude", "stopArea"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of stop_area
        if self.stop_area:
            _dict['stopArea'] = self.stop_area.to_dict()
        # set to None if platform (nullable) is None
        # and __fields_set__ contains the field
        if self.platform is None and "platform" in self.__fields_set__:
            _dict['platform'] = None

        # set to None if latitude (nullable) is None
        # and __fields_set__ contains the field
        if self.latitude is None and "latitude" in self.__fields_set__:
            _dict['latitude'] = None

        # set to None if longitude (nullable) is None
        # and __fields_set__ contains the field
        if self.longitude is None and "longitude" in self.__fields_set__:
            _dict['longitude'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel.parse_obj({
            "gid": obj.get("gid"),
            "name": obj.get("name"),
            "platform": obj.get("platform"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "stop_area": VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.from_dict(obj.get("stopArea")) if obj.get("stopArea") is not None else None
        })
        return _obj


