# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt
from openapi_client.models.vt_api_planera_resa_web_v4_models_journey_details_punch_configuration_duration_api_model import VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel

class VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel(BaseModel):
    """
    Represents punch configuration.  # noqa: E501
    """
    quota: Optional[StrictInt] = Field(None, description="Punch quota of a single ticket.")
    duration: Optional[VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel] = None
    __properties = ["quota", "duration"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of duration
        if self.duration:
            _dict['duration'] = self.duration.to_dict()
        # set to None if quota (nullable) is None
        # and __fields_set__ contains the field
        if self.quota is None and "quota" in self.__fields_set__:
            _dict['quota'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel:
        """Create an instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel.parse_obj(obj)

        _obj = VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel.parse_obj({
            "quota": obj.get("quota"),
            "duration": VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel.from_dict(obj.get("duration")) if obj.get("duration") is not None else None
        })
        return _obj


