# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VTApiPlaneraResaCoreModelsTransportMode(str, Enum):
    """
    VTApiPlaneraResaCoreModelsTransportMode
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    NONE = 'none'
    TRAM = 'tram'
    BUS = 'bus'
    FERRY = 'ferry'
    TRAIN = 'train'
    TAXI = 'taxi'
    WALK = 'walk'
    BIKE = 'bike'
    CAR = 'car'

    @classmethod
    def from_json(cls, json_str: str) -> VTApiPlaneraResaCoreModelsTransportMode:
        """Create an instance of VTApiPlaneraResaCoreModelsTransportMode from a JSON string"""
        return VTApiPlaneraResaCoreModelsTransportMode(json.loads(json_str))


